### ISSUE TITLE
To PMD4

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#102]
- [x] Add Cubes() to each transform.
- [x] Ensure family reference data can be loaded to PMD4 https://github.com/GSS-Cogs/pmd-jenkins-library/issues/17 and also https://github.com/GSS-Cogs/pmd-jenkins-library/issues/43
- [x] Codelist/concept schemes need catalogue entries. Part of https://github.com/GSS-Cogs/pmd-jenkins-library/issues/15
- [x] Sort out multi-measure GSS-Cogs/gss-utils#94, GSS-Cogs/gss-utils#93
- [x] Map each (dimension) column to the currently used codelist, using existing columns.csv -- could write a script to do this. GSS-Cogs/family-trade#103
- [x] Add measure type / value mapping for each pipeline. #104 
- [x] Compare results on trade.gss-data.org.uk with staging.gss-data.org.uk.
- [x] Deal with any yellow blobs. https://github.com/GSS-Cogs/pmd-jenkins-library/issues/37
