### ISSUE TITLE
HMRC_OTS

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#14]

**Comment by VTula2000** [comment]
Source data Url not available

**Comment by ajtucker** [comment]
It looks as though we merged the wrong branch (master) from the original repository.

**Comment by ajtucker** [comment]
This transform runs against some bespoke CSV files provided by HMRC.

We need to move to using published data instead, e.g. https://www.uktradeinfo.com/Statistics/Pages/DataDownloads.aspx

In the meantime I've updated the metadata and used gssutils.metadata.PMDDataset to create the trig.

**Comment by RedWalters** [comment]
- [x] **Does the dataset show up or is there an error?**
Yes and No
PMD4 : No

PMD3: http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc_ots_cn8

Dataset currently appears in PMD3 but errors out before being able to be opened (Server Error 500). This is currently causing the dataset to be inaccessible.

- [x] **Is it in the list of datasets from the main page?**
- [x] **Is there descriptive metadata on the search page?**

- [x] **Does transformed info match the original?**
Yes - Original data is in CSV format so minimal changes needed to be made, therefore little chance of loss of data during transform.
However, country codes have been changed to HMRC Partner Geography using GEONOM, this is apparently regularly updated and is currently using the 2018 list. 
This might need to be a note to update if new releases run through the pipeline.

- [x] **Does the tidydata download show all the data?**
Currently unable to test due to Server Error 500.

- [x] **Note differences in column/row headers**
'Foreign Country' has been changed to HMRC Partner Geography using Geonomenclature (GEONOM). See 'Does transformed info match the original?'
'comcode' has been merged with the observation year to make 'Combined Nomenclature', this will most likely need explanation somewhere on PMD as the header for this column is not self explanatory.

- [x] **Are there multiple cubes? List titles of cubes**
N/A : One cube. 

- [x] **What needs differentiating? Totals**
Country codes changed to HMRC Parnter Geography, see 'Does transformed info match the original?'

- [x] **Are there titles that need harmonising? World/Worldwide**
'Combined Nomenclature' is unclear as without context it's unknown what is being combined and that the contents of the column relate to.

- [x] **Does the structure look sensible?**
Yes. 
- [x] **Does the hierarchy work?**
Yes. 
- [x] **What needs further investigation or context?**
'Combined Nomenclature' may need context when presented.
- [x] **Any duplications?**
No.
- [x] **List any detailed metadata/methodology to add retrospectively**
Data is taken from Google drive rather than scraped from live page, this will mean that any releases will need to be manually updated as the newer datasets will have a different google drive reference.
Countries are mandated by Eurostat to use the Geonomenclature (GEONOM), which gradually changes over the years. 
HMRC keeps track of these changes to the country codes and numbers and their data for each year will use the latest GEONOM codes.

- [x] **Short metadata added**
N/A

**Comments:**

Review incomplete due to Server Error 500. Will need to return to finish once the error is fixed.

**Comment by JasonHowell** [comment]
@RedWalters JJ what's the latest with this one?  Thanks Jason.

**Comment by mikeAdamss** [comment]
@JasonHowell - this is fixed now and on pmd4 (as `Overseas Trade Statistics (CN8)`). Needs a BA review.

**Comment by JasonHowell** [comment]
BA's reviewed and good to go.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by canwaf** [comment]
This dataset is primed for a change to API/OData-based conversion into tidy data. The new source would be https://api.uktradeinfo.com/OTS.

**Comment by canwaf** [comment]
This is blocked pending the release of the API Download functionality to gss-utils.

**Comment by canwaf** [comment]
Talked this one over with @Tracey-B, this dataset has been renamed in AirTables to HMRC_OTS, and replaces the old CN8 version. The info.json has been updated accordingly.

**Comment by rossbowen** [comment]
When running `main.py` I get an error.

```python
ds = PMDDataset()
NameError: name 'PMDDataset' is not defined
```

**Comment by canwaf** [comment]
HMRC_OTS_CN8 is now HMRC_OTS. So this issue replaces the old directory.

**Comment by robons** [comment]
So I've found that there is a `SuppUnit` field being returned in the API data. It contains measure values which differ depending on which CN8 code the record is part of. I managed to stumble across the [mapping between the CN8 codes and the units of the value contained in the `SuppUnit` field](https://www.uktradeinfo.com/media/lmnfuqj5/2020-combined-nomenclature.xlsx). 

Unfortunately, it isn't clear what many of these units are. I have absolutely no idea what `pa` or `p/st`, `gi F/S` or `kg/net eda` or many of the other units mean. This part of the system seems to have been an afterthought.

Given that it's not clear how often this spreadsheet is likely to be updated, I'm unsure about what many of the units mean, and the large number of units we'd have to create here, I'm not going to include this field in the transformation.

@Tracey-B it might be worth getting back to the data producer to get them to provide a curated list of these units, their meanings and to perhaps include this information in the API somewhere so it's easier to find. I'd recomment renaming their `SuppUnit` field to `SuppValue` and adding a `SuppUnit` field which actually specifies what the unit is for the record -- ideally we'd be able to look this up within the API to get a suitable label.

@rossbowen FYI

**Comment by Tracey-B** [comment]
@robons I have just forwarded you a reply from HMRC and  cc'd @rossbowen

**Comment by robons** [comment]
I've made some changes to the [spec.md](https://github.com/GSS-Cogs/family-trade/blob/dbff1fd17088b6a6ee836dd31fc9602640333eaa/datasets/HMRC_OTS/spec.md#robs-recommendations) and put some provisional contents in the info.json file.

I presume you'll want to pick this up @canwaf ?

**Comment by canwaf** [comment]
# Tasks from `spec.md` linked above.
- [ ] Exclude columns as requested
- [ ] Map the `FlowTypeId` in the following fashion
- [ ] Add a Measure Type and Unit Type column
- [ ] ~~Pivot~~ **Melt** the df so that mass and GBP values appear in same columns (`value`,`measure-type`, `unit-type`) (see `spec.md`)
- [ ] Map suppression index

**Comment by canwaf** [comment]
Back over to you, @robons.

**Comment by robons** [comment]
@canwaf any chance you could make some changes to use the SITC code instead of the CN8 one? 

https://github.com/GSS-Cogs/family-trade/blob/b3692c3a62ea0c0365dc220255a32112c40c40a6/datasets/HMRC_OTS/spec.md#corrections

**Comment by canwaf** [comment]
- [ ] Refactor to change download behaviour to start at max available date and work backwards.

**Comment by robons** [comment]
@rossbowen @ajtucker We have a bit of a problem with this dataset. @canwaf FYI too.

I'd originally used the CN8 codelist to break this data up since it was the most granular. However, when doing this, I came across a problem where there appeared to be records which had the same dimension values (including CN8) but different SITC codes. I then assumed that HMRC wouldn't be insane, so I decided that the other commodity code (SITC) must be correctly partition the data.

Unfortunately, I was wrong. Neither CN8 not SITC fully partition the data. I have observed SITC codes vary whilst CN8 codes remain the same and vice versa.

For evidence of this, see the two below links. Note that the `CommodityId` code leads to the CN8 code value and that `CommoditySitcId` leads to the SITC code value.

[SITC varying as CommodityId (CN8) remains constant](https://api.uktradeinfo.com/OTS?$apply=groupby((CommoditySitcId,CommodityId))&$filter=CommodityId%20eq%2026).

[CommodityId (CN8) varying as SITC remains constant](https://api.uktradeinfo.com/OTS?$apply=groupby((CommoditySitcId,CommodityId))&$filter=CommoditySitcId%20eq%2028500).

So, it stands to reason that it is the combination of `(CN8, SITC)` together which partitions commodity space with CN8 sometimes being more specific and at other times SITC being more specific. 

Quite how we represent this in a single codeilst is beyond me. The most logical thing I can think to do is to provide two separate views over the data - one from the SITC perspective where we group data by SITC code and sum over any more specific CN8 codes and another view from the CN8 perspective where we group data by CN8 code and sum over any more specific SITC codes. Then we at least have hierarchies which we can use to help users navigate the codelists. 

How on earth HMRC expects anyone to understand and be able to work with this data is something that I do not understand at all.

**Comment by robons** [comment]
> The most logical thing I can think to do is to provide two separate views over the data - one from the SITC perspective where we group data by SITC code and sum over any more specific CN8 codes and another view from the CN8 perspective where we group data by CN8 code and sum over any more specific SITC codes. Then we at least have hierarchies which we can use to help users navigate the codelists.
> 

It appears that's the way HMRC do it too: 
[<img width="685" alt="image" src="https://user-images.githubusercontent.com/73846016/112950067-cafdfc80-9131-11eb-8bea-59dee7f30166.png">](https://www.uktradeinfo.com/trade-data/)

[<img width="1183" alt="image" src="https://user-images.githubusercontent.com/73846016/112950182-ea952500-9131-11eb-81d7-ea66a0e857fc.png">](https://www.uktradeinfo.com/trade-data/ots-custom-table/)

**Comment by Robsteranium** [comment]
I suppose it might seem a bit mad if you've not seen it before but it's actually quite common to provide multiple interpretations of a dataset using different coding systems. The ONS do it with MRETS to provide UK Trade in Goods by CPA, for example.

I guess the packaging mightn't be apparent from the API where you can select anything.

I would ideally like to:

- model the observations in the "original" encoding (i.e. however they were recorded as admin records)
- provide correspondence tables between the coding systems
- provide reinterpretations as "virtual releases" (i.e. automating the transformation from the original encoding to the users coding-of-choice).

We can use XKOS for this. I prepared a [Graphical description](https://docs.google.com/presentation/d/1FjE_84BvKoizeYZarVnXkMdTYHoE2wAmWhdKTsC9vrk/edit#slide=id.g42351f841b_0_194) and [RDF example](https://github.com/Swirrl/cogs-issues/blob/master/modelling/xkos/readme.md) in the GSS Alpha. The longer technical description gets stuck into the gory details of [apportionment](https://docs.google.com/document/d/1SZMoEMeQeSHy4RRkPeHzseXEMUULOhkhcdPDd68itcQ/edit#heading=h.omaq6a7ulqkx).

In this case, I presume the original encoding is HS. Judging by [this diagram](https://unstats.un.org/wiki/pages/viewpage.action?pageId=7405727) at least, the lookups from HS->CN and HS->SITC would only need be 1:n to lead to n:m CN<>SITC (indeed the reality is probably worse than that)! Indeed the diagram shows you how many possible choices of product encoding there are and why "virtual releases" might make for a nicer UX (i.e. becoming a data access concern not a cataloguing one).

For now, I'd suggest we do one of the following:

1. confirm the original encoding with HMRC and use that only
1. create separate cubes for each encoding (noting that we'd like to have something like a [publication resource](https://github.com/Swirrl/cogs-issues/issues/71) to collate them)
1. create a single (but sparse) cube with a control dimension (or ([namespace column](https://github.com/GSS-Cogs/gss-utils/issues/210#issuecomment-805838922)) to distinguish the encoding scheme

**Comment by robons** [comment]
@canwaf any chance you could alter the OData chunker functionality to use URLs like the following?

https://api.uktradeinfo.com/OTS?$filter=MonthId%20eq%20202001%20&$apply=groupby((MonthId,%20FlowTypeId,%20SuppressionIndex,%20CountryId,%20PortId,%20CommoditySitcId),%20aggregate(Value%20with%20sum%20as%20Value,%20NetMass%20with%20sum%20as%20NetMass))&$top=20

The alternative query to group by CommodityId (if we choose to proceed in that direction) is:
https://api.uktradeinfo.com/OTS?$filter=MonthId%20eq%20202001%20&$apply=groupby((MonthId,%20FlowTypeId,%20SuppressionIndex,%20CountryId,%20PortId,%20CommodityId),%20aggregate(Value%20with%20sum%20as%20Value,%20NetMass%20with%20sum%20as%20NetMass))&$top=20

Obviously, you'll want to remove the $top=20 param when running these for real.

**Comment by robons** [comment]
@rossbowen @ajtucker any suggestions about how you want to proceed with this dataset?

**Comment by canwaf** [comment]
Counter-offer for Wednesday (I'm off Tuesday).

- [ ] Output two csvs: one aggregated on CN8, the other aggregated on commitySitcId
- [ ] Magic

**Comment by robons** [comment]
Go ahead, one aggregates on CN8, the other aggregated on SitcCode please.

Just makesure they have unique dataset URIs. They should be distinct datasets.

**Comment by canwaf** [comment]
This was horrible, but it's now failing on SPARQL tests on codelists, back to you @robons.

**Comment by robons** [comment]
So there are now two datasets on PMD derived from the HMRC OTS data.

There is a view of the datacube from the SITC perspective and another from the CN8 perspective.
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/73846016/115401391-3e9ba280-a1e2-11eb-885b-ae0ead3d4cde.png">

@canwaf and I are going to run the build a few more times to ensure the multi-graph functionality works as expected.

The [CN8 codelist](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-overseas-trade-statistics%2Fhmrc-overseas-trade-statistics-cn8-catalog-entry&apply-filters=true) is derived from a combination of the *true* CN8 codelist (published by eurostat/ramon) and the codelist that the HMRC provides. Unfortunately the data in some places is very messy and contains what I would consider to be duplicated concepts/nodes/labels; this is not something we can reasonably correct given that the HMRC API is the source for these duplications (and some concepts which have an entirely missing label).

Both the CN8 and SITCv4 codelists seem to be a bit too large for PMD to handle comfortably and result in incredibly poor loading times which makes it difficult to filter the dataset down. In addition, PMD does not seem to be paying attention to the concept sort order and so we seem to get concepts displaying in an unhelpful order with `Other products` showing up first when `SECTION I - LIVE ANIMALS; ANIMAL PRODUCTS` should show up first.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/73846016/115402272-2d06ca80-a1e3-11eb-9b47-629cc3b80dd6.png">

Another problem these datasets highlight again is that we can't collapse nodes in the hierarchical view of the codelist making it very difficult to navigate ones of this size.

**Comment by Robsteranium** [comment]
Yeah the sorting doesn't look right there. I'll raise this on the Muttnik repo.

The "drilldown view" collapses nodes.

The slow loading is unfortunate but it's an 18M download for CN8! It does appear to work eventually (i.e. within timeouts).

We should probably look to present larger codelists like this (say 500+ concepts) using the geo-picker UI instead (albeit without a map). That is designed to load resources incrementally (instead of all up front) based upon levels in the hierarchy. In terms of the data, this would mean adding [pmdkos:ConceptLevel](https://github.com/Swirrl/cogs-issues/blob/master/resources/pmdkos.ttl) sub-classes to codes for things like "HS Heading" and "HS Subheading" etc. IIRC we would also need to add a (TBC) property to describe the status. @RicSwirrl - perhaps something for Q2?

Is the repetition of "hmrc-overseas-trade-statistics" in the URIs deliberate? What about "hmrc-overseas-trade-statistics/sitc/" and "hmrc-overseas-trade-statistics/cn8/"? Might sound trivial but over nearly 1.5m observations that'll be quite a saving. There's also a double "//", it ought to be sufficient to take e.g. "month/2021-02" only for ref-ints.

**Comment by robons** [comment]
Right, we've successfully got the accretive upload working on this. It's slowly progressing through the HMRC data and uploading it into a large number of graphs (one per month). 

Assuming nothing goes wrong, it'll take the process approximately *17 days* to pull in all of the data from 2000-01 to 2021-02. (It takes approx 1h45m to import each month's data) and I estimate that it'll mean we generate somewhere in the region of 0.5 terrabytes of uncompressed TTL triples.

Given how long it takes to upload this one large data-set, and the corresponding storage requirements, I do question how large we really want to go in future.

So @Tracey-B I'd say now is as good a time as any to review this dataset and point out the problems with it.

**Comment by robons** [comment]
> Yeah the sorting doesn't look right there. I'll raise this on the Muttnik repo.
> 
> The "drilldown view" collapses nodes.
> 
Indeed, but the drilldown view removes the context that's often useful when looking at codelists.

> The slow loading is unfortunate but it's an 18M download for CN8! It does appear to work eventually (i.e. within timeouts).
> 
> We should probably look to present larger codelists like this (say 500+ concepts) using the geo-picker UI instead (albeit without a map). That is designed to load resources incrementally (instead of all up front) based upon levels in the hierarchy. In terms of the data, this would mean adding [pmdkos:ConceptLevel](https://github.com/Swirrl/cogs-issues/blob/master/resources/pmdkos.ttl) sub-classes to codes for things like "HS Heading" and "HS Subheading" etc. IIRC we would also need to add a (TBC) property to describe the status. @RicSwirrl - perhaps something for Q2?
> 
> Is the repetition of "hmrc-overseas-trade-statistics" in the URIs deliberate? What about "hmrc-overseas-trade-statistics/sitc/" and "hmrc-overseas-trade-statistics/cn8/"? Might sound trivial but over nearly 1.5m observations that'll be quite a saving. There's also a double "//", it ought to be sufficient to take e.g. "month/2021-02" only for ref-ints.

Yes, the repetition is due to the codelist being local (specific to) to the dataset. The URI is a based on a convention we use for all of our datasets' codelists.

**Comment by RicSwirrl** [comment]
Thanks for mentioning me @Robsteranium

We can definitely look into what's happening with the sort priorities. Did you make a muttnik issue already?

As Robin says, the geo-browser/picker (actually intended to be generic to 'levels'), could be used here. Originally we'd hoped that we wouldn't have huge codelists which weren't level-oriented, so we could avoid having the extra complexity of incrementally loading the data on the other views (and changing how search worked inside schemes). But if that's not the case we can certainly look into it! 

As Rob mentions we could additionally look into making tree view nodes optionally collapsible.

I think the existing ways to browse concept schemes are all useful in their own ways, but I accept the use-case coverage isn't exhaustive! Anything is possible - its just a matter of picking the right stuff to focus on. :)

**Comment by Robsteranium** [comment]
> 17 days ... 0.5 terrabytes

I think we should aim to cover this comprehensively, but I'm not sure we should aim for that right now.

On the one hand it'll be a good performance test, particularly for the multigraph-cube model.

On the other hand it might make more sense to wait until we've further explored the scaling options under consideration.

In the meantime I think it would be acceptable to load the last few years of data only.

---

> Indeed, but the drilldown view removes the context that's often useful when looking at codelists.

It removes parent-siblings (Auntie codes, if you like :D) but the direct ancestors (being the most important context) are visible in the crumb-trail.

The structural search will take the approach you're suggesting. Nodes are presented in a tree which is collapsed by default and each parent has a twiddly disclosure control to un-collapse (and so load) its children.

It that proves to be more popular then we could always review the Muttnik designs later.

---

Muttnik issue for sort priority: https://github.com/Swirrl/muttnik/issues/1130.

---

Shall we create a new thread/ to-do for adding levels to e.g. CN8 and SITC4 including the data, modelling and UI changes?

**Comment by OluEA** [comment]
BA Checks complete. This transformation is via an API. Following conversions with @robons the transformation seems reasonable. 
**Observations:**
-Unable to filter by month, measure type or unit of measure.
-Unable to sort due to datasets being too large

It's suggested that this be passed to HMRC to carry our a more thorough check to ensure the accuracy of the data before being published.

**Comment by Robsteranium** [comment]
It looks like some of the observations at least (e.g. [this first one](http://gss-data.org.uk/data/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8/1/eu-exports/01041080/000//id/month/2019-05/monetary-value)) are duplicated - i.e. the same resource+description exists in two graphs (in this case http://gss-data.org.uk/graph/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8 and http://gss-data.org.uk/graph/gss_data/trade/hmrc-overseas-trade-statistics-cn8/201905). Perhaps some old state was left behind or maybe the accretive upload isn't partitioning exclusively?

In any case this will have a performance penalty (and could potentially break stuff that doesn't guard against unexpected cardinality).

**Comment by robons** [comment]
> It looks like some of the observations at least (e.g. [this first one](http://gss-data.org.uk/data/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8/1/eu-exports/01041080/000//id/month/2019-05/monetary-value)) are duplicated - i.e. the same resource+description exists in two graphs (in this case http://gss-data.org.uk/graph/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8 and http://gss-data.org.uk/graph/gss_data/trade/hmrc-overseas-trade-statistics-cn8/201905). Perhaps some old state was left behind or maybe the accretive upload isn't partitioning exclusively?
> 
> In any case this will have a performance penalty (and could potentially break stuff that doesn't guard against unexpected cardinality).

Is this on beta or staging @Robsteranium?

**Comment by Robsteranium** [comment]
Sorry, this is [on the beta site](https://beta.gss-data.org.uk/resource?uri=http://gss-data.org.uk/data/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8/1/eu-exports/01041080/000//id/month/2019-05/monetary-value).

**Comment by Robsteranium** [comment]
We might want to split this out into a separate issue but the concepts (e.g. [live sheep](https://beta.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2FHMRC-overseas-trade-statistics%23concept%2Fcn8%2F01041080)) appear to have a `skos:exactMatch` to a string `"http://gss-data.org.uk/def/trade/concept/combined-nomenclature-8/2021/01041080"` when they ought to point at a URI.

**Comment by robons** [comment]
> We might want to split this out into a separate issue but the concepts (e.g. [live sheep](https://beta.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2FHMRC-overseas-trade-statistics%23concept%2Fcn8%2F01041080)) appear to have a `skos:exactMatch` to a string `"http://gss-data.org.uk/def/trade/concept/combined-nomenclature-8/2021/01041080"` when they ought to point at a URI.

Thanks for highlighting that. I've put in a fix. 

And I'm currently in the process of wiping and re-uploading the data on beta so we should be able to get rid of those duplicates soon.

**Comment by Robsteranium** [comment]
The country dimensions (i.e. from the [SITC](http://gss-data.org.uk/data/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-sitc#dimension/country_id
) and [CN8](http://gss-data.org.uk/data/gss_data/trade/hmrc-overseas-trade-statistics/hmrc-overseas-trade-statistics-cn8#dimension/country_id) subsets) need harmonising with a parent property. I'm not sure whether you would prefer to link directly to `sdmxd:refArea` or continue with the report/partner geography hierarchy (or perhaps the HMRC/ ONS split thereof) we reached in the alpha.

Likewise the flow types dimensions ought to be sub properties of http://gss-data.org.uk/def/trade/property/dimension/flow-directions.

Further to [@OluEA's comment](https://github.com/GSS-Cogs/family-trade/issues/14#issuecomment-827540607) - some filter controls are absent because we're missing codelists for the Month and Measure type dimensions (on both SITC and CN8 versions). We wouldn't typically expect to filter by Unit as this is an attribute property, not a dimension property, and so isn't responsible for identifying individual observations (it's descriptive not structural). In effect, filtering by measure will tend to also filter by unit. That said, I suppose it's reasonable feature request, particularly for other attributes like observation-status that won't have a 1:1 relationship with another dimension - e.g. "find all redacted values" (cc @RicSwirrl).

**Comment by Robsteranium** [comment]
It looks like some of the CN8 product codes (which IIRC are derived as part of this dataset) have truncated labels e.g. 
[08119039](https://beta.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2FHMRC-overseas-trade-statistics%23concept%2Fcn8%2F08119039).

**Comment by robons** [comment]
> It looks like some of the CN8 product codes (which IIRC are derived as part of this dataset) have truncated labels e.g.
> [08119039](https://beta.gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2FHMRC-overseas-trade-statistics%23concept%2Fcn8%2F08119039).

Unfortunately, the data has this problem [at source](https://api.uktradeinfo.com/Commodity?$top=10&$filter=Cn8Code%20eq%20%2708119039%27).

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/73846016/129687089-f02e6612-922f-4549-a499-d7a095f7269b.png">
