### ISSUE TITLE
Scheduling Jenkins Pipelines to run when there has been a new release using CRON. 

### ISSUE THREAD

**Issue by Shannon95** [GSS-Cogs/family-trade#171]
Implementation required to schedule each Trade dataset pipeline to rerun on the latest publication. 
Things to do:
- [x]  Investigation on each pipeline needed to determine the latest and next release of each publication. (Can be found [here](https://docs.google.com/spreadsheets/d/1E2MbgtP0rE9rT-h7S55qDZ_YcbIF7LeaSmEJ2c-jBxY/edit?usp=sharing) )

Implementation required on following pipelines/issues:
- [x] [ONS-balance-of-payments](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-balance-of-payments/) [#1](https://github.com/GSS-Cogs/family-trade/issues/1)  
Quarterly Publication.
would next run on Thursday, September 30, 2021 and December 30,2021 at 11:01:21 AM BST or via GitHub hook trigger.

- [x] [ONS-UK-SA-Trade-in-goods](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-SA-Trade-in-goods/) [#2](https://github.com/GSS-Cogs/family-trade/issues/2)
Monthly Publication.
Running next 5th-11th day of every month of  2021 at  11:01 am BST or via GitHub hook trigger.

- [x]  [ONS-UK-trade-in-goods-by-industry-country-and-commodity](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-goods-by-industry-country-and-commodity/) [#3](https://github.com/GSS-Cogs/family-trade/issues/3)
Annual Publication.
Running next 27 May 2022 at 10:35 am BST or via GitHub hook trigger.

- [x] [ONS-International-Trade-in-Services](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-International-Trade-in-Services/) [#4](https://github.com/GSS-Cogs/family-trade/issues/4)
Annual Publication.
Running next 28 Jan 2022 at 10:53 am GMT or via GitHub hook trigger.

- [x] [ONS_MRETS](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS_MRETS/) [#5](https://github.com/GSS-Cogs/family-trade/issues/5)
Monthly Publication. Given the history of releases, it will run on the last day of first week every month.
Running next 10 July - December 2021 at 10:01 am BST & GMT or via GitHub hook trigger.

- [x] [ONS-UK-Total-trade](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-Total-trade/) [#6](https://github.com/GSS-Cogs/family-trade/issues/6)
Published every 5 months
Running next 6 August 2021 at 10:38 am BST or via GitHub hook trigger.

- [x] [ONS-GDP-at-current-prices-real-time-database-YBHA](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-GDP-at-current-prices-real-time-database-YBHA/) [#7](https://github.com/GSS-Cogs/family-trade/issues/7)
Published every 5 months. The next release not stated, however, an assumption has been made.
Running next 13 August 2021 and 13 November 2021 at 10:12 am BST 

- [x] [HMRC-trade-in-goods-by-business-characteristics](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-trade-in-goods-by-business-characteristics/) [#8](https://github.com/GSS-Cogs/family-trade/issues/8)
Published Annually. The next release not stated, however, an assumption has been made.
Running next 24-26th November 2021 at 10:01 am GMT

- [x] [ONS-Trade-in-goods](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Trade-in-goods/) [#9](https://github.com/GSS-Cogs/family-trade/issues/9)
Monthly Publication.
Running next on 6-10th of every month of 2021 at 11:31:13 AM BST & GMT or via GitHub hook trigger.

- [x] [ONS-UK-Ecconomic-Accounts-balance-of-payments-current-account](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-Economic-Accounts-balance-of-payments-current-account/) [#11](https://github.com/GSS-Cogs/family-trade/issues/11)
Published for every three months on March, June, September, December. Given the history of previous releases, it was mostly released on the last day of the month.
Running next on 30 June, September, December, 2021 & March 2022, at 10:01:29 AM BST  & GMT

- [x] [HMRC-regional-trade-statistics](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-regional-trade-statistics/) [#12](https://github.com/GSS-Cogs/family-trade/issues/12)
The next release date is unknown - scheduled for twice a year in the meantime. 

- [x] [ONS-Quarterly-National-Accounts](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Quarterly-National-Accounts/) [#13](https://github.com/GSS-Cogs/family-trade/issues/13)
Published for every three months on the second week of May, August, November and February 2021 and 2022
Running next on 13 August, November and February 2021 and 2022 at 10:10 am BST and GMT

- [x] [HMRC-overseas-trade-statistics](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-overseas-trade-statistics/) [#14](https://github.com/GSS-Cogs/family-trade/issues/14)
Monthly publication. The next release date is not stated, by looking at the previous releases, an assumption has been made to run at the end of the second week.
Running next on 17 July, Aug, Sep, Oct, Nov Dec 2021 10:05 am BST & GMT

- [x] [ONS-UK-Trade-in-goods-CPA-08 ](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-Trade-in-goods-CPA-08/)[#15](https://github.com/GSS-Cogs/family-trade/issues/15)
Published Quarterly. The next release date is 16 June 2021. Looking at the previous release it is assumed that the next release will happen in the second week of September and December.
Running next on 15-18 June, September, December 2021 11:01 am BST & GMT

- [x] [HMRC-RTS-Small-area](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-RTS-Small-area/) [#16](https://github.com/GSS-Cogs/family-trade/issues/16)
Published Annually. The next release date not stated, by looking at the previous releases, an assumption has been made to run at the end of the first week of November.
Running next on Friday, 05 November 2021, 10:05 am GMT

- [x] [ONS-UK-trade-in-services](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-services/) [#17](https://github.com/GSS-Cogs/family-trade/issues/17)
Published Quarterly. The next release date is not stated, by looking at the previous releases, an assumption has been made to run at the end of the first week of August and November.
Running next on 06 August & November 2021, 10:19 am BST & GMT

- [x] [ONS_CPA](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS_CPA/) [#18](https://github.com/GSS-Cogs/family-trade/issues/18)
Published Quarterly. The next release is on 15 September 2021.
Running next on 15-17 September, December 2021 and March 2022 10:01 am BST & GMT

- [x] [ONS-International-exports-of-services-from-subnational-areas-of-the-UK](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-International-exports-of-services-from-subnational-areas-of-the-UK/) [#24](https://github.com/GSS-Cogs/family-trade/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+)
The next release date is unknown - scheduled for twice a year in the meantime. 

- [x] [ONS-REUK-Service](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-REUK-Service/) [#25](https://github.com/GSS-Cogs/family-trade/issues/25)
The next release date is unknown - scheduled for twice a year in the meantime. 

- [x] [ONS-foreign-direct-investment-involving-uk-companies](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-foreign-direct-investment-involving-uk-companies/) [#28](https://github.com/GSS-Cogs/family-trade/issues/28)
next release date is unknown - shedualed for twice a year in meantime. 

- [x] [Annual Business Survey exporters and importers (ABS)](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS_ABS/) [#32](https://github.com/GSS-Cogs/family-trade/issues/32)
Annual Publication
would next run on Friday, November 19, 2021, 10:39:10 AM GMT.

- [x] [ONS-BOP-individual-country-data](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-BOP-individual-country-data/) [#33](https://github.com/GSS-Cogs/family-trade/issues/33)
next release date is unknown - shedualed for twice a year in meantime. 

- [x] [ONS-pink-book-trade-in-services](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-pink-book-trade-in-services/)[ #34](https://github.com/GSS-Cogs/family-trade/issues/34)
The next release is not stated, however, an assumption has been made that it could be an annual publication. 
would next run on Friday, October 29, 2021, 10:20:08 AM BST.

- [x] [HMRC-alcohol-bulletin](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-alcohol-bulletin/) [#67](https://github.com/GSS-Cogs/family-trade/issues/67)
Published Quarterly. 
would next run on Friday, August 27, 2021, 10:38:58 AM BST.

- [x] [ONS-Regional-gross-domestic-product-city-regions](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Regional-gross-domestic-product-city-regions/) [#79](https://github.com/GSS-Cogs/family-trade/issues/79)
The next release is not stated, however, an assumption has been made that it could be an annual publication. 
would next run on Thursday, May 26, 2022, 10:05:09 AM BST.

- [x] [ONS-UK-trade-in-services-by-industry-country-and-service-type-exports](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-services-by-industry-country-and-service-type-exports/) [ #80](https://github.com/GSS-Cogs/family-trade/issues/80)
The next release is not stated, however, an assumption has been made that it could be an annual publication. 
would next run on Thursday, May 26, 2022, 10:47:53 AM BST.

- [x] [ONS-Exports-of-services-by-country-by-modes-of-supply](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Exports-of-services-by-country-by-modes-of-supply/) [#83](https://github.com/GSS-Cogs/family-trade/issues/83) (Pipeline also includes ONS-Imports-of-services-by-country-by-modes-of-supply #88 )
The next release is not stated, however, an assumption has been made that it could be an annual publication. 
would next run on Friday, November 26, 2021, 10:57:18 AM GMT  or via GitHub hook trigger.

- [x] [ONS-International-trade-in-services-by-subnational-areas-of-the-UK](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/) [#84](https://github.com/GSS-Cogs/family-trade/issues/84)
The next release is not stated, however, an assumption has been made that it could be an annual publication. 
would next run on Friday, September 10, 2021, 10:10:57 AM BST or via GitHub hook trigger.

- [x] [ONS-Quarterly-country-and-regional-GDP](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-Quarterly-country-and-regional-GDP/) [#85](https://github.com/GSS-Cogs/family-trade/issues/85)
New publication released every 3 months: Feb, May, Aug, Nov. Though dates/days do not seem to be consistent, from what I can tell by looking at previous releases they are released at some point within the first week of the month so have set the pipeline to run on the 8th of every 3rd month defined above. This will need to be checked. 
would next run on Thursday, August 8, 2021, 10:42:25 AM BST  or via GitHub hook trigger.

- [x] [DCMS-Sectors-Economic-Estimates-Year-Trade-in-services](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/DCMS-Sectors-Economic-Estimates-Year-Trade-in-services/) [#86](https://github.com/GSS-Cogs/family-trade/issues/86)
Annual publication. 
Running next 11 Feb 2022 at 10:07 am or via GitHub hook trigger. 
- [x] [HMRC-Regional-trade-statistics-interactive-analysis](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/HMRC-Regional-trade-statistics-interactive-analysis/) [#87](https://github.com/GSS-Cogs/family-trade/issues/87)
Annual publication.
Running next 11 June 2021 at 11:53 am BST or via GitHub hook trigger.

- [x] [ONS-UK-trade-in-services-by-business-characteristics](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/ONS-UK-trade-in-services-by-business-characteristics/) [#89](https://github.com/GSS-Cogs/family-trade/issues/89) 
next release date is unknown - scheduled for twice a year in the meantime.

 [DIT-UK-tariffs](https://ci.floop.org.uk/job/GSS_data/job/beta.gss-data.org.uk/job/family/job/trade/job/DIT-UK-tariffs/) [#114](https://github.com/GSS-Cogs/family-trade/issues/114) (Need to have a convo on how to approach this as the approach is different)
