### ISSUE TITLE
Migrating Trade to PMD4

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#77]
- [ ] Use PMD4 API/auth0 GSS-Cogs/family-trade#76
- [ ] Use table2qb in Jenkins pipeline GSS-Cogs/pmd-jenkins-library#25
- [ ] Ensure ICs are up to date GSS-Cogs/gdp-sparql-tests#4

Additional/optional:

- [ ] ensure `dcat:theme` is set.
- [ ] re-do codelists / dimensions
- [ ] scraper improvements feedback from DIT
- [ ] remove measure-type codelists
- [ ] rename as per GSS-Cogs/family-trade#75

**Comment by JasonHowell** [comment]
@ajtucker  are the above still validate?
